

export const json = {
   "data": {
      "events": [
         {
            "id": 1,
            "mapid": 1,
            "format": 1,
            "name": "Windmill Hill Nov08 Selection Race",
            "date": "2008-11-15",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 2,
            "mapid": 2,
            "format": 1,
            "name": "Henley Gate 06 Dec 08 Saturday Series",
            "date": "2008-12-06",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 3,
            "mapid": 3,
            "format": 1,
            "name": "SN Trophy Dec 2008",
            "date": "2008-12-28",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 4,
            "mapid": 4,
            "format": 1,
            "name": "Witley - Saturday Series",
            "date": "2009-01-10",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 6,
            "mapid": 5,
            "format": 1,
            "name": "BNOC 2009 (v2)",
            "date": "2009-01-24",
            "club": "Southern Navigators",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 7,
            "mapid": 6,
            "format": 1,
            "name": "SN Starurday\/Junior League 2009 #6",
            "date": "2009-01-31",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 10,
            "mapid": 9,
            "format": 1,
            "name": "Junior League #7\/2009",
            "date": "2009-03-07",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 11,
            "mapid": 10,
            "format": 1,
            "name": "Sn Saturday Junior League #1",
            "date": "2009-09-19",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 12,
            "mapid": 11,
            "format": 1,
            "name": "SN Trophy 2009",
            "date": "2009-11-08",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 13,
            "mapid": 12,
            "format": 1,
            "name": "Junior League 2009\/10 #3",
            "date": "2009-11-14",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 14,
            "mapid": 13,
            "format": 1,
            "name": "SN Saturday Series - Mytchett",
            "date": "2009-12-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 15,
            "mapid": 14,
            "format": 1,
            "name": "SN Saturday Series - Velmead Common",
            "date": "2010-01-16",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 16,
            "mapid": 15,
            "format": 1,
            "name": "SN Saturday Series - Eagle House",
            "date": "2010-02-06",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 17,
            "mapid": 16,
            "format": 1,
            "name": "Saturday Series - Witley",
            "date": "2010-02-27",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 18,
            "mapid": 18,
            "format": 1,
            "name": "Evening Training Race",
            "date": "2010-07-14",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 19,
            "mapid": 19,
            "format": 1,
            "name": "SN Handicap 2010",
            "date": "2010-09-02",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 20,
            "mapid": 20,
            "format": 1,
            "name": "JL2010, Ev#1",
            "date": "2010-09-18",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 21,
            "mapid": 21,
            "format": 1,
            "name": "JL 2010 EV#2\/YBT",
            "date": "2010-10-09",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 22,
            "mapid": 22,
            "format": 1,
            "name": "Wisley JL#3",
            "date": "2010-11-13",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 23,
            "mapid": 23,
            "format": 1,
            "name": "SN Trophy 2010",
            "date": "2010-11-28",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 24,
            "mapid": 24,
            "format": 1,
            "name": "Saturday Series",
            "date": "2011-01-15",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 25,
            "mapid": 25,
            "format": 1,
            "name": "Henley Gate JL Event",
            "date": "2011-02-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 26,
            "mapid": 26,
            "format": 1,
            "name": "Saturday Series - Merrist Wood",
            "date": "2011-03-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 27,
            "mapid": 27,
            "format": 1,
            "name": "WOC2011",
            "date": "2011-04-03",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 28,
            "mapid": 29,
            "format": 1,
            "name": "Saturday Series 2011\/12 #1",
            "date": "2011-09-17",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 29,
            "mapid": 30,
            "format": 1,
            "name": "Saturday Series 2011\/12 #2",
            "date": "2011-10-15",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 30,
            "mapid": 31,
            "format": 1,
            "name": "SN Trophy 2011",
            "date": "2011-11-13",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 31,
            "mapid": 32,
            "format": 1,
            "name": "Saturday Series 2011\/12 - #3",
            "date": "2011-11-19",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 32,
            "mapid": 33,
            "format": 1,
            "name": "Saturday Series 2011\/12 - Ev#4",
            "date": "2011-12-10",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 33,
            "mapid": 34,
            "format": 1,
            "name": "Saturday Series 2011\/12 - Ev#5",
            "date": "2012-01-14",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 34,
            "mapid": 35,
            "format": 1,
            "name": "Saturday Series 2011\/12 - Ev#6",
            "date": "2012-02-04",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 35,
            "mapid": 36,
            "format": 1,
            "name": "Saturday Series 2011\/12 - Ev#7",
            "date": "2012-02-25",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 36,
            "mapid": 29,
            "format": 1,
            "name": "Saturday Series 2012\/13 - Ev#1",
            "date": "2012-09-15",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 37,
            "mapid": 38,
            "format": 1,
            "name": "Saturday Series 2012\/13 - Ev#2",
            "date": "2012-10-13",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 38,
            "mapid": 39,
            "format": 1,
            "name": "Saturday Series 2012\/13 - Ev#3",
            "date": "2012-11-10",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 39,
            "mapid": 40,
            "format": 1,
            "name": "SN Urban Race 2012",
            "date": "2012-11-24",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 40,
            "mapid": 41,
            "format": 1,
            "name": "SN Trophy 2012",
            "date": "2012-11-25",
            "club": "Southern Navigators",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 41,
            "mapid": 42,
            "format": 1,
            "name": "Saturday Series 2012\/13 - Ev#4",
            "date": "2012-12-15",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 43,
            "mapid": 43,
            "format": 1,
            "name": "Night Event Frith Hill",
            "date": "2013-01-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 42,
            "mapid": 43,
            "format": 1,
            "name": "Saturday Series 2012\/13 - Ev#5",
            "date": "2013-01-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 44,
            "mapid": 43,
            "format": 2,
            "name": "Virtual - Frith Hill",
            "date": "2013-01-20",
            "club": "Southern Navigators",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 45,
            "mapid": 35,
            "format": 1,
            "name": "Saturday Series 2012\/13 - Ev#6",
            "date": "2013-02-02",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 46,
            "mapid": 44,
            "format": 1,
            "name": "Saturday Series 2012\/13 - Ev#7",
            "date": "2013-03-02",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 47,
            "mapid": 45,
            "format": 2,
            "name": "Virtual - Whitmoor",
            "date": "2013-03-25",
            "club": "Southern Navigators",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 48,
            "mapid": 46,
            "format": 1,
            "name": "SEOA\/SCOA Middle Championships 2013",
            "date": "2013-04-07",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 49,
            "mapid": 47,
            "format": 1,
            "name": "SE Sprints - Heat1",
            "date": "2013-05-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 51,
            "mapid": 48,
            "format": 1,
            "name": "SE Sprints Heat 2",
            "date": "2013-05-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 52,
            "mapid": 49,
            "format": 1,
            "name": "SN Urban Race 2013",
            "date": "2013-07-20",
            "club": "Southern Navigators",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 53,
            "mapid": 50,
            "format": 1,
            "name": "Saturday Series 2013\/14 - Ev#1",
            "date": "2013-09-14",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 54,
            "mapid": 51,
            "format": 1,
            "name": "Saturday Series 2013\/14 - Ev#2",
            "date": "2013-10-12",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 55,
            "mapid": 53,
            "format": 1,
            "name": "SN Trophy 2013",
            "date": "2013-11-10",
            "club": "Southern Navigators",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 56,
            "mapid": 54,
            "format": 1,
            "name": "Saturday Series 2013\/14 - Ev#3",
            "date": "2013-11-16",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 57,
            "mapid": 55,
            "format": 1,
            "name": "Saturday Series 2013\/14 Ev#4",
            "date": "2013-12-14",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 58,
            "mapid": 56,
            "format": 1,
            "name": "Saturday Series 2013\/14 Ev#5",
            "date": "2014-01-11",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 59,
            "mapid": 57,
            "format": 1,
            "name": "2014-01-11 Saturday Series 2013\/14 Ev#7 ",
            "date": "2014-03-01",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 60,
            "mapid": 58,
            "format": 1,
            "name": "SNSS 2014-15 #1 Horsell Common",
            "date": "2014-09-13",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 61,
            "mapid": 59,
            "format": 1,
            "name": "SN Trophy 2014",
            "date": "2014-11-08",
            "club": "Southern Navigators",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 62,
            "mapid": 60,
            "format": 1,
            "name": "Farnborough Urban Race",
            "date": "2014-11-29",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 63,
            "mapid": 43,
            "format": 1,
            "name": "SNSS 2015 #3",
            "date": "2014-12-06",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 64,
            "mapid": 61,
            "format": 1,
            "name": "CompassSport Cup Final 2014",
            "date": "2014-12-14",
            "club": "Southern Navigators",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 65,
            "mapid": 62,
            "suffix": "gif",
            "format": 1,
            "name": "SS2015#4",
            "date": "2015-01-10",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 66,
            "mapid": 63,
            "suffix": "gif",
            "format": 1,
            "name": "SN Sat Series - Velmead",
            "date": "2015-02-07",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 67,
            "mapid": 64,
            "suffix": "gif",
            "format": 1,
            "name": "SN Sat Series 2015\/16 #2 Wisley",
            "date": "2015-10-03",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 68,
            "mapid": 65,
            "suffix": "gif",
            "format": 1,
            "name": "Hindhead Schools Event ",
            "date": "2015-11-14",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 69,
            "mapid": 66,
            "suffix": "gif",
            "format": 1,
            "name": "Horsell Common SN SS ",
            "date": "2015-12-05",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 70,
            "mapid": 67,
            "format": 1,
            "name": "SN Trophy",
            "date": "2015-12-20",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 71,
            "mapid": 68,
            "format": 1,
            "name": "SN Saturday series LVS",
            "date": "2016-01-09",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 72,
            "mapid": 69,
            "suffix": "gif",
            "format": 1,
            "name": "Eagle House Schools Event",
            "date": "2016-01-30",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 73,
            "mapid": 70,
            "suffix": "gif",
            "format": 1,
            "name": "Witley Schools League Event",
            "date": "2016-02-27",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 74,
            "mapid": 71,
            "suffix": "gif",
            "format": 3,
            "name": "2016 PrizeGiving",
            "date": "2016-03-19",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 75,
            "mapid": 72,
            "format": 1,
            "name": "UK Urban League - Woking",
            "date": "2016-07-16",
            "club": "SN",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 76,
            "mapid": 73,
            "format": 1,
            "name": "SN SS 2016\/17 Frith Hill",
            "date": "2016-09-17",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 77,
            "mapid": 74,
            "format": 1,
            "name": "SN, SLOW Club Champs",
            "date": "2016-12-03",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 78,
            "mapid": 75,
            "suffix": "gif",
            "format": 1,
            "name": "SN trophy 2016",
            "date": "2016-12-11",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 79,
            "mapid": 76,
            "suffix": "gif",
            "format": 1,
            "name": "Wisley West SNSS",
            "date": "2017-01-14",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 80,
            "mapid": 77,
            "suffix": "gif",
            "format": 1,
            "name": "SN SS Horsell Common",
            "date": "2017-02-04",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 81,
            "mapid": 78,
            "suffix": "gif",
            "format": 1,
            "name": "SN Saturday schools - Frensham heights",
            "date": "2017-03-04",
            "club": "Southern Navigators",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 82,
            "mapid": 79,
            "suffix": "gif",
            "format": 1,
            "name": "SN Urban - Farnborough",
            "date": "2017-08-20",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 83,
            "mapid": 80,
            "suffix": "gif",
            "format": 1,
            "name": "Merrist SS 2017\/18 #1",
            "date": "2017-09-16",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 84,
            "mapid": 81,
            "suffix": "gif",
            "format": 1,
            "name": "JIRC 2017 - Individual",
            "date": "2017-09-23",
            "club": "SN",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 85,
            "mapid": 82,
            "format": 3,
            "name": "JIRC Relay - Blackheath",
            "date": "2017-09-24",
            "club": "SN",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 86,
            "mapid": 83,
            "suffix": "gif",
            "format": 1,
            "name": "Alice Schools Event #3",
            "date": "2017-11-11",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 87,
            "mapid": 84,
            "format": 1,
            "name": "Alice SEOA Night champs",
            "date": "2017-11-11",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 88,
            "mapid": 85,
            "suffix": "gif",
            "format": 1,
            "name": "Wisley SN\/SLOW Champs",
            "date": "2017-12-02",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 89,
            "mapid": 86,
            "suffix": "gif",
            "format": 1,
            "name": "SN Trophy 2017 - Ash rages",
            "date": "2017-12-17",
            "club": "SN",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 90,
            "mapid": 87,
            "format": 1,
            "name": "SN Saturday schools - Eagle House",
            "date": "2018-01-27",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 97,
            "mapid": 93,
            "suffix": "gif",
            "format": 1,
            "name": "Esher Schools",
            "date": "2018-02-17",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 91,
            "mapid": 78,
            "suffix": "gif",
            "format": 1,
            "name": "Frensham Heights Saturday Event",
            "date": "2018-03-17",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 98,
            "mapid": 94,
            "suffix": "gif",
            "format": 2,
            "name": "Woking Score",
            "date": "2018-04-28",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 92,
            "mapid": 88,
            "suffix": "gif",
            "format": 3,
            "name": "Staines Massive",
            "date": "2018-06-23",
            "club": "Southern Navigators",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 93,
            "mapid": 89,
            "suffix": "gif",
            "format": 1,
            "name": "Horsell schools event",
            "date": "2018-09-08",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 99,
            "mapid": 95,
            "suffix": "gif",
            "format": 1,
            "name": "Frimley Fuel Saturday Event",
            "date": "2018-10-06",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 100,
            "mapid": 96,
            "suffix": "gif",
            "format": 2,
            "name": "Witley Saturday Schools Event",
            "date": "2018-11-10",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 94,
            "mapid": 90,
            "suffix": "gif",
            "format": 1,
            "name": "Southern Champs (Hindhead\/Devils Punch Bowl)",
            "date": "2018-11-25",
            "club": "SN",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 95,
            "mapid": 91,
            "suffix": "gif",
            "format": 1,
            "name": "Wellington College",
            "date": "2018-12-30",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 96,
            "mapid": 92,
            "format": 1,
            "name": "Merrist Woods Saturday Event",
            "date": "2019-01-19",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 101,
            "mapid": 97,
            "suffix": "gif",
            "format": 1,
            "name": "Horsell Common Saturday Series",
            "date": "2019-02-09",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 102,
            "mapid": 98,
            "suffix": "gif",
            "format": 1,
            "name": "Wisley West",
            "date": "2019-03-09",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 103,
            "mapid": 99,
            "suffix": "gif",
            "format": 1,
            "name": "Alice Holt 2019",
            "date": "2019-04-06",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 104,
            "mapid": 101,
            "suffix": "gif",
            "format": 1,
            "name": "Frimley Urban",
            "date": "2019-07-07",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 105,
            "mapid": 102,
            "suffix": "gif",
            "format": 1,
            "name": "SN Sprint Woking",
            "date": "2019-08-31",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 106,
            "mapid": 103,
            "suffix": "gif",
            "format": 1,
            "name": "SN Sprint Gordons",
            "date": "2019-08-31",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 107,
            "mapid": 104,
            "suffix": "gif",
            "format": 1,
            "name": "Witley Common saturday schools",
            "date": "2019-11-09",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 108,
            "mapid": 105,
            "suffix": "gif",
            "format": 1,
            "name": "SN Trophy 2019",
            "date": "2019-11-17",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 109,
            "mapid": 106,
            "suffix": "gif",
            "format": 1,
            "name": "Merrist Wood Saturday Series",
            "date": "2019-12-14",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 110,
            "mapid": 107,
            "suffix": "gif",
            "format": 1,
            "name": "Normandy Xmas Middle",
            "date": "2019-12-27",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 111,
            "mapid": 108,
            "suffix": "gif",
            "format": 1,
            "name": "Wisley SN Saturday Series",
            "date": "2020-01-11",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 112,
            "mapid": 109,
            "suffix": "gif",
            "format": 1,
            "name": "Alice Holt Saturday Series",
            "date": "2020-03-07",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 113,
            "mapid": 110,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O - Pyestock",
            "date": "2020-03-21",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 117,
            "mapid": 115,
            "format": 2,
            "name": "Solo-O Frith",
            "date": "2020-05-20",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 114,
            "mapid": 111,
            "format": 2,
            "name": "Solo-O Barossa",
            "date": "2020-05-20",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 116,
            "mapid": 114,
            "format": 2,
            "name": "Solo-O Minley",
            "date": "2020-05-20",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 115,
            "mapid": 112,
            "format": 2,
            "name": "Solo-O Hawley",
            "date": "2020-05-20",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 118,
            "mapid": 116,
            "format": 2,
            "name": "Solo-O Mytchett West",
            "date": "2020-06-09",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 119,
            "mapid": 116,
            "format": 2,
            "name": "Solo-O Mytchett East",
            "date": "2020-06-09",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 120,
            "mapid": 117,
            "format": 2,
            "name": "Solo-O Windmill Hill",
            "date": "2020-06-09",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 121,
            "mapid": 119,
            "format": 2,
            "name": "Solo-O Bramshott South",
            "date": "2020-06-18",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 122,
            "mapid": 120,
            "format": 2,
            "name": "Barossa 2 - SoloO",
            "date": "2020-07-04",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 124,
            "mapid": 121,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Pyestock Oct 2020",
            "date": "2020-10-28",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 123,
            "mapid": 122,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Windmill Hill Nov 2020",
            "date": "2020-11-04",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 125,
            "mapid": 123,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Barossa Nov 2020",
            "date": "2020-11-07",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 126,
            "mapid": 124,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Mytchett Nov 2020",
            "date": "2020-11-14",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 127,
            "mapid": 125,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O LVS Nov 2020",
            "date": "2020-11-21",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 128,
            "mapid": 126,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Bramshott Nov 20",
            "date": "2020-11-21",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 129,
            "mapid": 127,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Hawley Nov 20",
            "date": "2020-11-24",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 130,
            "mapid": 128,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Minley Dec 20",
            "date": "2020-12-11",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 131,
            "mapid": 129,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Frith Hill Dec 20",
            "date": "2020-12-12",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 132,
            "mapid": 130,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O - Ash Dec 20",
            "date": "2020-12-19",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 133,
            "mapid": 131,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Rushmoor",
            "date": "2021-01-08",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 134,
            "mapid": 132,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O Congo Jan21",
            "date": "2021-01-13",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 135,
            "mapid": 133,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O LVS Jan 21",
            "date": "2021-01-19",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 136,
            "mapid": 134,
            "suffix": "gif",
            "format": 2,
            "name": "Solo-O LVS March 2021",
            "date": "2021-03-31",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 137,
            "mapid": 135,
            "suffix": "gif",
            "format": 1,
            "name": "SheepHouse Activity",
            "date": "2021-04-10",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 138,
            "mapid": 136,
            "suffix": "gif",
            "format": 1,
            "name": "Alice Holt Summer restart",
            "date": "2021-06-12",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 139,
            "mapid": 137,
            "suffix": "gif",
            "format": 1,
            "name": "SN Urban Goldsworth Park &amp; Horsell",
            "date": "2021-08-30",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 140,
            "mapid": 138,
            "suffix": "gif",
            "format": 1,
            "name": "Southwood Country Park",
            "date": "2021-09-25",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 141,
            "mapid": 139,
            "suffix": "gif",
            "format": 1,
            "name": "Horsell Common SN SS",
            "date": "2021-10-16",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 142,
            "mapid": 140,
            "suffix": "gif",
            "format": 1,
            "name": "SN Trophy 2021 - Long Valley North",
            "date": "2021-11-14",
            "club": "SN",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 143,
            "mapid": 141,
            "suffix": "gif",
            "format": 1,
            "name": "Wisley SS",
            "date": "2021-11-27",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 144,
            "mapid": 142,
            "suffix": "gif",
            "format": 1,
            "name": "SN Club champs",
            "date": "2021-12-05",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 145,
            "mapid": 143,
            "suffix": "gif",
            "format": 1,
            "name": "Witley Common ",
            "date": "2022-01-15",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 146,
            "mapid": 144,
            "suffix": "gif",
            "format": 1,
            "name": "Sn Night Training Puttenham",
            "date": "2022-02-16",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 147,
            "mapid": 145,
            "suffix": "gif",
            "format": 1,
            "name": "Eagle House ",
            "date": "2022-02-19",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 148,
            "mapid": 146,
            "suffix": "gif",
            "format": 1,
            "name": "Alice Holt Saturday Series",
            "date": "2022-03-19",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 149,
            "mapid": 147,
            "suffix": "gif",
            "format": 1,
            "name": "Farnham Park Saturday Series",
            "date": "2022-04-23",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 150,
            "mapid": 148,
            "suffix": "gif",
            "format": 1,
            "name": "Hogmoor Inclosure YBT",
            "date": "2022-05-14",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 151,
            "mapid": 149,
            "suffix": "gif",
            "format": 1,
            "name": "SN Handicap 2022",
            "date": "2022-05-25",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 152,
            "mapid": 150,
            "suffix": "gif",
            "format": 1,
            "name": "SN Urban Cove Brook",
            "date": "2022-07-16",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 153,
            "mapid": 151,
            "suffix": "gif",
            "format": 1,
            "name": "NRA Training",
            "date": "2022-08-03",
            "club": "SN",
            "type": "T",
            "locked": false,
            "comment": ""
         },
         {
            "id": 154,
            "mapid": 152,
            "suffix": "gif",
            "format": 1,
            "name": "Frimley Fuel Allotments Sprint",
            "date": "2022-09-24",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 155,
            "mapid": 153,
            "suffix": "gif",
            "format": 1,
            "name": "Ravenscote Sprint",
            "date": "2022-09-24",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 156,
            "mapid": 154,
            "suffix": "gif",
            "format": 1,
            "name": "Southwood Country Park",
            "date": "2022-10-15",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 157,
            "mapid": 155,
            "suffix": "gif",
            "format": 1,
            "name": "SN Trophy 2022 - Long Valley South",
            "date": "2022-11-13",
            "club": "SN",
            "type": "N",
            "locked": false,
            "comment": ""
         },
         {
            "id": 158,
            "mapid": 156,
            "suffix": "gif",
            "format": 1,
            "name": "Horsell Common SN SS",
            "date": "2022-12-10",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 159,
            "mapid": 157,
            "suffix": "gif",
            "format": 1,
            "name": "Wellington College Post Xmas Run",
            "date": "2022-12-29",
            "club": "SN",
            "type": "R",
            "locked": false,
            "comment": ""
         },
         {
            "id": 160,
            "mapid": 158,
            "suffix": "gif",
            "format": 1,
            "name": "Wellesley Woods SS",
            "date": "2023-01-14",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         },
         {
            "id": 161,
            "mapid": 159,
            "suffix": "gif",
            "format": 1,
            "name": "Frensham Heights Saturday Series",
            "date": "2023-02-11",
            "club": "SN",
            "type": "L",
            "locked": false,
            "comment": ""
         }
      ],
      "API version": "1.10.2"
   }
}